standingssync/urls.py
"""Routes for standingssync."""

from django.urls import path

from . import views

app_name = "standingssync"

urlpatterns = [
    path("", views.index, name="index"),
    path("characters", views.characters, name="characters"),
    path("add-character", views.add_character, name="add_character"),
    path(
        "remove-character/<int:alt_pk>", views.remove_character, name="remove_character"
    ),
    path(
        "add-alliance-manager", views.add_alliance_manager, name="add_alliance_manager"
    ),
    path("wars", views.wars, name="wars"),
    path("admin-update-wars", views.admin_update_wars, name="admin_update_wars"),
]

standingssync/templates/standingssync/_base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load static %}

{% block page_title %}{% translate app_title %}{% endblock %}
{% block content %}
    <br />
    {% include 'standingssync/partial/menu.html' %}
    <h2>{{ page_title }}</h2>
    {% block details %}{% endblock %}
{% endblock %}

{% block extra_css %}
    <link href="{% static 'standingssync/base.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

standingssync/templates/standingssync/characters.html
{% extends 'standingssync/_base.html' %}
{% load i18n %}
{% load humanize %}

{% block details %}

    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Alliance for Sync' %}</h3>
        </div>
        <div class="panel-body">
            {% if alliance %}
                <img class="ra-avatar img-circle" src="{{ alliance.logo_url }}">
                &nbsp;&nbsp;
                {{ alliance.alliance_name }}
                &nbsp;
                (
                {% if alliance_contacts_count != None %}
                    {{ alliance_contacts_count }} contacts
                    {% if alliance_war_targets_count != None %}
                        ,
                    {% endif %}
                {% endif %}
                {% if alliance_war_targets_count != None %}
                    {{ alliance_war_targets_count }} war targets
                {% endif %}
                )
            {% else %}
                <p class="text-muted">Not configured</p>
            {% endif %}
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Your Synced Characters' %}</h3>
        </div>
        <div class="panel-body">
            {% if has_synced_chars %}
                <table class="table table-striped" id="tab_standingssync">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Organization</th>
                            <th>Status</th>
                            <th>Disable</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for character in synced_characters|dictsort:"name" %}
                            {% if character.errors %}
                                <tr class="danger">
                            {% else %}
                                <tr>
                            {% endif %}
                                    <td>
                                        <img src="{{ character.portrait_url }}" class="ra-avatar img-circle">
                                        &nbsp;
                                        {{ character.name }}
                                    </td>
                                    <td>{{ character.organization }}</td>
                                    <td>
                                        {% if character.errors %}
                                            {% for error in character.errors %}
                                                <span class="text-warning">
                                                    <i class="fas fa-info-circle"></i>
                                                    {{ error }}
                                                </span><br>
                                            {% endfor %}
                                        {% else %}
                                            <i class="fas fa-check text-success"></i>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a  class="btn btn-danger"
                                            href="{% url 'standingssync:remove_character' character.pk %}"
                                            role="button">
                                            <i class="far fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="text-muted">None</p>
            {% endif %}
        </div>
    </div>

    {% if alliance %}
        <a  id="standingssyncBtnAddSyncChar"
            class="btn btn-primary"
            href="{% url 'standingssync:add_character' %}">
            Add Character to Sync
        </a>
    {% else %}
        <button class="btn btn-primary" disabled="disabled">
            Add Character to Sync
        </button>
    {% endif %}

    <div class="bs-callout bs-callout-warning">
        <h3>Read Me First</h3>
        <p>Once activated this app will automatically update the personal contacts of your synced characters. Note that you can only sync out-of-alliance alts.</p>
        {% if alliance_contacts_count != None %}
            <h4>Alliance Contacts</h4>
            <p>
                All personal contacts will be replaced with alliance contacts allowing you to see alliance standings on your synced characters.
            </p>
            <p>
                <i class="fas fa-exclamation-triangle"></i> You will loose all personal contacts on your synced characters.
            </p>
        {% endif %}
        {% if alliance_war_targets_count != None %}
            <h4>War Targets</h4>
            <p>Adds current alliance war targets as personal contacts with -10 standing a personal contact to your synced characters. If the contact already exists it will be overwritten. War targets can be distinguished by having the war targets contact label.</p>
            <p><i class="fas fa-info-circle"></i>
                Please make sure to create a contact label with the name "{{ war_targets_label_name }}" on all your synced characters.
            </p>
        {% endif %}
    </div>

{% endblock %}

standingssync/templates/standingssync/wars.html
{% extends 'standingssync/_base.html' %}
{% load i18n %}
{% load humanize %}
{% load standingssync %}

{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{{ alliance }} [{{ active_wars_count }} active wars]</h3>
        </div>
        <div class="panel-body">
            <div role="tabpanel" class="tab-pane">
                <table class="table table-striped table-width-fix" id="tab-active-wars">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Start</th>
                            <th>Aggressor</th>
                            <th>Defender</th>
                            <th>Allies</th>
                            <th>Finish</th>
                            <th>Active</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for war in wars %}
                            <tr>
                                <td data-sort="{{ war.state }}">
                                    {% if war.state == State.PENDING %}
                                        <i class="fas fa-pause text-warning" title="pending"></i>
                                    {% elif war.state == State.FINISHED %}
                                        <i class="fas fa-stop text-success" title="finished"></i>
                                    {% else %}
                                        <i class="fas fa-play text-danger" title="active"></i>
                                    {% endif %}
                                </td>
                                <td data-sort="{{ war.started.isoformat }}" class="text-nowrap">
                                    <span title="{{ war.started|date:DATEFORMAT }}">
                                        {{ war.started|naturaltime }}
                                    </span>
                                </td>
                                <td data-sort="{{ war.aggressor }}">
                                    {% war_participant war.aggressor %}
                                </td>
                                <td data-sort="{{ war.defender }}">
                                    {% war_participant war.defender %}
                                </td>
                                <td>
                                    {% for ally in war.allies %}
                                        {% war_participant ally %}<br>
                                    {% empty %}
                                        -
                                    {% endfor %}
                                </td>
                                <td data-sort="{{ war.finished.isoformat }}" class="text-nowrap">
                                    {% if war.finished %}
                                        <span title="{{ war.finished|date:DATEFORMAT }}">
                                            {{ war.finished|naturaltime }}
                                        </span>
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td>
                                    {% if war.is_active %}yes{% else %}no{% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <p class="text-muted">
        <i class="fas fa-pause text-warning"></i>&nbsp;&nbsp;Pending war
        &nbsp;&nbsp;&nbsp;
        <i class="fas fa-play text-danger"></i>&nbsp;&nbsp;Active war
        &nbsp;&nbsp;&nbsp;
        <i class="fas fa-stop text-success"></i>&nbsp;&nbsp;Finished war
    </p>
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    {% include 'bundles/filterdropdown-js.html' %}

    <script type="application/javascript">
        $(document).ready(function () {
            $('#tab-active-wars').DataTable({
                paging: false,
                info: false,
                order: [ [1, "desc"] ],
                columnDefs: [
                    {
                        sortable: false, targets: [ 4 ]
                    },
                    {
                        visible: false, targets: [ 6 ]
                    }
                ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 6
                        }
                    ],
                    autoSize: false,
                    bootstrap: true
                }
            });
        });
    </script>
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {% include 'bundles/datatables-css.html' %}
{% endblock %}