standingssync/urls.py
"""Routes for standingssync."""

from django.urls import path

from . import views

app_name = "standingssync"

urlpatterns = [
    path("", views.index, name="index"),
    path("characters", views.characters, name="characters"),
    path("add-character", views.add_character, name="add_character"),
    path(
        "remove-character/<int:alt_pk>", views.remove_character, name="remove_character"
    ),
    path(
        "add-alliance-manager", views.add_alliance_manager, name="add_alliance_manager"
    ),
    path("wars", views.wars, name="wars"),
    path("admin-update-wars", views.admin_update_wars, name="admin_update_wars"),
]

standingssync/templates/standingssync/partial/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'standingssync:characters' %}">{{ app_title }}</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'standingssync:characters' %}">
                    <a href="{% url 'standingssync:characters' %}">My Characters</a>
                </li>
                {% if STANDINGSSYNC_ADD_WAR_TARGETS %}
                    <li class="{% navactive request 'standingssync:wars' %}">
                        <a href="{% url 'standingssync:wars' %}">
                            Current Wars
                        </a>
                    </li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">

                {% if perms.standingssync.add_syncmanager %}
                    <a class="btn btn-default navbar-btn" href="{% url 'standingssync:add_alliance_manager' %}">
                        Set Alliance Character
                    </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

standingssync/templates/standingssync/partial/war_participant.html
{% if has_data %}
    <img src="{{ icon_url }}" height="{{ icon_size }}" width="{{ icon_size }}">&nbsp;
    <a href="{{ profile_url }}" target="_blank">{{ name }}</a>
{% else %}
    [NO DATA]
{% endif %}